name: Definition of Done
on:
  pull_request:
    types: [opened, edited]

concurrency:
  group: ci-{{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-dod:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Check DoD
        uses: platisd/definition-of-done@master
        with:
          dod_yaml: '.github/dod.yml'
          message_header: 'The A11y and PO reviews will only take place after all other DoD steps have been completed by the Developer:'
          github_token: ${{ secrets.GITHUB_TOKEN }}
